# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  displayName: Install .NET 6
  inputs:
    packageType: 'sdk'
    version: '6.0.x'  
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '_src/Blog.Builder.sln'
    arguments: '--configuration Release --output ../_last_build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '_output/'
    skip_app_build: true
    azure_static_web_apps_api_token: '$(deployment_token)'